// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Game() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"m-0 p-0 w-100 vh-100 container-fluid\"><div class=\"m-0 p-1 w-100 vh-100 row\"><section class=\"mr-1 ml-0 my-0 p-0 col-12 col-md-9 d-flex flex-column\"><div id=\"chess-board\" class=\"card bg flex-grow-1\"></div></section><section class=\"m-0 p-0 col-12 col-md-3 d-flex flex-column\"><div id=\"game-moves\" class=\"mb-1 card bg flex-grow-1\"></div><div id=\"user-info\" class=\"card bg text d-flex flex-column flex-bias-25\"><div class=\"d-flex flex-column\"><span>Name</span> <span id=\"user-info-name\"></span></div><div class=\"d-flex flex-column\"><span>Elo</span> <span id=\"user-info-elo\"></span></div></div></section></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
