// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"m-0 p-0 w-100 vh-100 d-flex flex-column align-items-center justify-content-center\"><h1>Welcome to <strong>ZugZwang</strong>!</h1><h6 class=\"mt-3\">A custom built chess engine written with Go and Templ.</h6><div class=\"d-flex flex-column w-100 mt-5 align-items-center justify-content-center\"><p>Please enter your name, estimated ELO, and what strength of <i>ZugZwang</i> you want to play against.</p><div class=\"d-flex flex-column mt-3 w-25\"><label for=\"name\">Name</label> <input class=\"mt-1 w-100\" id=\"name\" name=\"name\"></div><div class=\"d-flex flex-column mt-3 w-25\"><label for=\"elo\">Elo</label> <input class=\"mt-1 w-100\" id=\"elo\" name=\"elo\" type=\"number\"></div><div class=\"d-flex flex-column mt-3 w-25\"><label for=\"strength\">Engine Strength (Estimated ELO not availible yet)</label> <select class=\"mt-1 w-100\" id=\"strength\" name=\"strength\"><option value=\"Strong\">Strong</option> <option value=\"Good\">Good</option> <option value=\"Weak\">Weak</option></select></div></div><div class=\"d-flex flex-row align-items-center justify-content-center gap-2 mt-4\"><button class=\"btn-primary\" id=\"start-game\">Start Game</button> <button class=\"btn-secondary\" hx-get=\"/learn-more\" hx-target=\"#root\" hx-push-url=\"true\">Learn More</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
